server:
  port: 8080
  servlet:
    context-path: /moap-pg

spring:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/moap?ApplicationName=moap-pg
    username: frodo
    password: frodo123
    hikari:
      maximum-pool-size: 5

hibernate:
  dialect: org.hibernate.dialect.PostgreSQLDialect
